# Generated by Django 5.1.15 on 2026-02-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_name', models.CharField(max_length=120)),
                ('created_by_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.TextField()),
                ('background', models.TextField(blank=True)),
                ('aims', models.TextField(blank=True)),
                ('methods', models.TextField(blank=True)),
                ('skills_needed', models.CharField(blank=True, max_length=240)),
                ('time_commitment', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INPROG', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=400)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portal.proposal')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer_name', models.CharField(max_length=120)),
                ('volunteer_email', models.EmailField(max_length=254)),
                ('interest_reason', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='portal.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SignupAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.proposalquestion')),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='portal.signup')),
            ],
            options={
                'unique_together': {('signup', 'question')},
            },
        ),
    ]
