# Generated by Django 5.1.15 on 2026-02-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='owner_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
