# Generated by Django 5.1.15 on 2026-02-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_proposal_owner_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
    ]
