# Generated by Django 5.1.15 on 2026-02-25 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_signup_decided_at_signup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='proposalquestion',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='volunteer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='volunteer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='signupanswer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.AlterUniqueTogether(
            name='signupanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='time_commitment',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='decided_at',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='interest_reason',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='owner_token',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tags',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='proposalquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposalquestion',
            name='prompt',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='signupanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='portal.proposalquestion'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='proposals', to='portal.tag'),
        ),
    ]
